function mricrogl_command = generate_montage_mricrogl(uimg, oimgs, colnames, mosaic, varargin)

clim = [0 1];
for i = 1:length(varargin)
    if ischar(varargin{i})
        switch varargin{i}
            case {'clim'}
                clim = varargin{i+1};
                assert(numel(clim)==2 & isnumeric(clim));
        end
    end
end

mricrogl_command = ['import gl', newline, ...
    'gl.resetdefaults()', newline, ...
    'gl.backcolor(255,255,255)', newline, ...
    'gl.colorbarposition(0)', newline, ...
    sprintf('gl.loadimage("%s")', uimg), newline];

for oimg_i = 1:numel(oimgs)
    mricrogl_command = [mricrogl_command, ...
        sprintf(['gl.overlayloadsmooth(1)', newline, ...
        'gl.overlaymaskwithbackground(1)', newline, ...
        'gl.overlayload("%s")', newline, ...
        'gl.colorname(%d, "%s")', newline, ...
        'gl.minmax(1, %f, %f)', newline, ...
        'gl.zerointensityinvisible(1, 1)', newline], ...
        oimgs{oimg_i}, ...
        oimg_i, colnames{oimg_i}, ...
        clim(1), clim(2))];
end

mricrogl_command = [mricrogl_command, ...
    sprintf('gl.mosaic("%s")', mosaic), newline];

end